package org.vanilladb.core.latch.csv;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

public class CsvWriter<R extends CsvRow> {
	private String fileName;

	public CsvWriter(String fileName) {
		this.fileName = fileName;
	}
	
	public void generateOutputFile(String header, List<R> rows) {
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
			
			writer.append(header + "\n");
			for (R row : rows) {
				writer.append(row.toRow() + "\n");
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
		System.out.println(String.format("%s is generated by data collector", fileName));
	}
}
