package org.vanilladb.core.latch.csv;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CsvWriter<R extends CsvRow> {
	private static Logger logger = Logger.getLogger(CsvWriter.class.getName());
	private String fileName;

	public CsvWriter(String fileName) {
		this.fileName = fileName + ".csv";
	}

	public void generateOutputFile(String header, List<R> rows) {
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {

			writer.append(header + "\n");
			for (R row : rows) {
				writer.append(row.toRow() + "\n");
			}
		} catch (IOException e) {
			e.printStackTrace();
		}

		if (logger.isLoggable(Level.INFO)) {
			String log = String.format("%s is generated by data collector", fileName);
			logger.info(log);
		}
	}
}
